import { iso } from "./common";
import { serializeInvoiceLine } from "./lines";
import type { Invoice, InvoiceLine, Customer, Payment } from "@/generated/prisma/client";
import { serializePayment } from "./payment";

export type InvoiceWithOptionalRelations = Invoice & { lines?: InvoiceLine[]; customer?: Customer; payments?: Payment[] };

export function serializeInvoice(inv: InvoiceWithOptionalRelations, embed: Set<string>) {
  return {
    objectName: "Invoice" as const,
    id: inv.id,
    number: inv.number,
    status: inv.status,
    type: inv.type,
    taxScheme: inv.taxScheme,
    customerId: inv.customerId,
    contactPersonId: inv.contactPersonId,
    billingAddressId: inv.billingAddressId,
    shippingAddressId: inv.shippingAddressId,
    currency: inv.currency,
    issueDate: iso(inv.issueDate),
    deliveryDate: iso(inv.deliveryDate),
    deliveryStart: iso(inv.deliveryStart),
    deliveryEnd: iso(inv.deliveryEnd),
    dueDate: iso(inv.dueDate),
    buyerReference: inv.buyerReference,
    subject: inv.subject,
    orderNumber: inv.orderNumber,
    notes: inv.notes,
    paymentTerms: inv.paymentTerms,
    headerText: inv.headerText,
    footerText: inv.footerText,
    documentDiscountPermille: inv.documentDiscountPermille,
    documentDiscountCents: inv.documentDiscountCents,
    documentChargePermille: inv.documentChargePermille,
    documentChargeCents: inv.documentChargeCents,
    documentChargeReason: inv.documentChargeReason,
    skonto1Permille: inv.skonto1Permille,
    skonto1Days: inv.skonto1Days,
    skonto2Permille: inv.skonto2Permille,
    skonto2Days: inv.skonto2Days,
    paymentMethodId: inv.paymentMethodId,
    netTotalCents: inv.netTotalCents,
    taxTotalCents: inv.taxTotalCents,
    grossTotalCents: inv.grossTotalCents,
    paidAmountCents: inv.paidAmountCents,
    payableCents: inv.payableCents,
    prepaidCents: inv.prepaidCents,
    reversedByInvoiceId: inv.reversedByInvoiceId,
    correctsInvoiceId: inv.correctsInvoiceId,
    recurringInvoiceId: inv.recurringInvoiceId,
    sourceType: inv.sourceType,
    sourceId: inv.sourceId,
    partialPermille: inv.partialPermille,
    xmlFormat: inv.xmlFormat,
    finalizedAt: iso(inv.finalizedAt),
    dunningState: inv.dunningState,
    dunningPausedUntil: iso(inv.dunningPausedUntil),
    dunningStateNote: inv.dunningStateNote,
    createdAt: iso(inv.createdAt),
    updatedAt: iso(inv.updatedAt),
    ...(embed.has("customer") && inv.customer ? { customerName: inv.customer.name } : {}),
    ...(embed.has("lines") ? { lines: (inv.lines ?? []).map(serializeInvoiceLine) } : {}),
    ...(embed.has("payments") ? { payments: (inv.payments ?? []).map(serializePayment) } : {}),
  };
}
